### ISSUE TITLE
Can not connect to Gateway after the client restart.

### ISSUE THREAD

**Issue by satoshikumano** [KiiPlatform/gateway-agent#136]
gateway-agent: 4253e67fd38c38a16b7c1dbd5e73cca9435a8bad
gwc-cli: KiiPlatform/gwc-cli@143285eda88402feff4f8976de5827478883e892

Steps:
- Up gateway-agent
```shell
./gateway-agent
```

- Connect End node
```shell
./gwc-cli -evid node1 -aname master
Ctrl + C
./gwc-cli -evid node1 -aname master
```

```
panic: Connection Refused, not authorized

goroutine 1 [running]:
panic(0x2a4a60, 0xc8200a05bb)
	/usr/local/go/src/runtime/panic.go:464 +0x3e6
main.connectToLocalBroker(0xc8200a0148, 0x8, 0xc8200b0160, 0x20, 0xc8200a0180, 0x2, 0xc8200a0260, 0xa, 0xfd008, 0x0, ...)
	/Users/satoshi/.godir/src/github.com/KiiPlatform/gwc-cli/mqtt_client.go:23 +0x3f2
main.main()
	/Users/satoshi/.godir/src/github.com/KiiPlatform/gwc-cli/main.go:65 +0x36e
```

Need to restart gateway-agent to recover.

**Comment by taro-m** [comment]
fixed by go-mqtt https://github.com/koron/go-mqtt/commit/0e364a4721120e49c0420cae628f215b505b1746

**Comment by satoshikumano** [comment]
Thanks!
Confirmed fix.
