### ISSUE TITLE
test failed by paho's double close

### ISSUE THREAD

**Issue by taro-m** [KiiPlatform/gateway-agent#183]
occasionally happend when run `go test -race` at tests/integration/restore.

```
panic: close of closed channel

goroutine 85 [running]:
panic(0xa36ac0, 0xc0822f69f0)
        C:/Local/Go/go1.6.windows-amd64/src/runtime/panic.go:464 +0x40d
github.com/eclipse/paho%2emqtt%2egolang.(*client).internalConnLost(0xc0821c0000, 0x2468940, 0xc0822fe280)
        C:/Users/koron/gowork/src/github.com/eclipse/paho.mqtt.golang/client.go:406 +0x57
github.com/eclipse/paho%2emqtt%2egolang.alllogic(0xc0821c0000)
        C:/Users/koron/gowork/src/github.com/eclipse/paho.mqtt.golang/net.go:271 +0x4ddf
created by github.com/eclipse/paho%2emqtt%2egolang.(*client).Connect.func1
        C:/Users/koron/gowork/src/github.com/eclipse/paho.mqtt.golang/client.go:233 +0x1937
exit status 2
FAIL    github.com/KiiPlatform/gateway-agent/tests/integration/restore  13.691s
```

**Comment by taro-m** [comment]
It looks like paho have a kind of race problem.
When MQTT server shutdown and client `Disconnect()` at almost same time it will be happen.

**Comment by taro-m** [comment]
PRed to paho https://github.com/eclipse/paho.mqtt.golang/pull/44

**Comment by taro-m** [comment]
have merged to paho
